module.exports = {
  mySidebar: [
    {
      type: "category",
      label: "Setup",
      items: [
        {
          type: "autogenerated",
          dirName: "01-basics",
        },
      ],
    },
    {
      type: "category",
      label: "Platforms",
      items: [
        {
          type: "autogenerated",
          dirName: "04-platforms",
        },
      ],
    },
	{
      type: "category",
      label: "Core Concepts",
      items: [
        {
          type: "autogenerated",
          dirName: "03-guides",
        },
      ],
    },
  ],
};
