module.exports = {
  mySidebar: [
    {
      type: "category",
      label: "Setup",
      items: [
        {
          type: "autogenerated",
          dirName: "01-basics",
        },
      ],
    },
  ],
};
