//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct AudioSettingsDefaultDeviceInternalEnumDTO : System.IEquatable<AudioSettingsDefaultDeviceInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<AudioSettingsDefaultDeviceInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly AudioSettingsDefaultDeviceInternalEnumDTO Speaker = new AudioSettingsDefaultDeviceInternalEnumDTO("speaker");
        public static readonly AudioSettingsDefaultDeviceInternalEnumDTO Earpiece = new AudioSettingsDefaultDeviceInternalEnumDTO("earpiece");

        public AudioSettingsDefaultDeviceInternalEnumDTO(string value)
        {
            Value = value;
        }

        public AudioSettingsDefaultDeviceInternalEnumDTO Parse(string value) => new AudioSettingsDefaultDeviceInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(AudioSettingsDefaultDeviceInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is AudioSettingsDefaultDeviceInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(AudioSettingsDefaultDeviceInternalEnumDTO left, AudioSettingsDefaultDeviceInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(AudioSettingsDefaultDeviceInternalEnumDTO left, AudioSettingsDefaultDeviceInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator AudioSettingsDefaultDeviceInternalEnumDTO(string value) => new AudioSettingsDefaultDeviceInternalEnumDTO(value);

        public static implicit operator string(AudioSettingsDefaultDeviceInternalEnumDTO type) => type.Value;
    }
}
