//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// CallClosedCaption represents a closed caption of a call.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class CallClosedCaptionInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("end_time", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset EndTime { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("speaker_id", Required = Newtonsoft.Json.Required.Default)]
        public string SpeakerId { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("start_time", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset StartTime { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("text", Required = Newtonsoft.Json.Required.Default)]
        public string Text { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("user", Required = Newtonsoft.Json.Required.Default)]
        public UserResponseInternalDTO User { get; set; } = new UserResponseInternalDTO();

    }

}

