//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct CreateDeviceRequestPushProviderInternalEnumDTO : System.IEquatable<CreateDeviceRequestPushProviderInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<CreateDeviceRequestPushProviderInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly CreateDeviceRequestPushProviderInternalEnumDTO Firebase = new CreateDeviceRequestPushProviderInternalEnumDTO("firebase");
        public static readonly CreateDeviceRequestPushProviderInternalEnumDTO Apn = new CreateDeviceRequestPushProviderInternalEnumDTO("apn");
        public static readonly CreateDeviceRequestPushProviderInternalEnumDTO Huawei = new CreateDeviceRequestPushProviderInternalEnumDTO("huawei");
        public static readonly CreateDeviceRequestPushProviderInternalEnumDTO Xiaomi = new CreateDeviceRequestPushProviderInternalEnumDTO("xiaomi");

        public CreateDeviceRequestPushProviderInternalEnumDTO(string value)
        {
            Value = value;
        }

        public CreateDeviceRequestPushProviderInternalEnumDTO Parse(string value) => new CreateDeviceRequestPushProviderInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(CreateDeviceRequestPushProviderInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is CreateDeviceRequestPushProviderInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(CreateDeviceRequestPushProviderInternalEnumDTO left, CreateDeviceRequestPushProviderInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(CreateDeviceRequestPushProviderInternalEnumDTO left, CreateDeviceRequestPushProviderInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator CreateDeviceRequestPushProviderInternalEnumDTO(string value) => new CreateDeviceRequestPushProviderInternalEnumDTO(value);

        public static implicit operator string(CreateDeviceRequestPushProviderInternalEnumDTO type) => type.Value;
    }
}
