//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct FrameRecordingSettingsRequestModeInternalEnumDTO : System.IEquatable<FrameRecordingSettingsRequestModeInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<FrameRecordingSettingsRequestModeInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly FrameRecordingSettingsRequestModeInternalEnumDTO Available = new FrameRecordingSettingsRequestModeInternalEnumDTO("available");
        public static readonly FrameRecordingSettingsRequestModeInternalEnumDTO Disabled = new FrameRecordingSettingsRequestModeInternalEnumDTO("disabled");
        public static readonly FrameRecordingSettingsRequestModeInternalEnumDTO Auto_On = new FrameRecordingSettingsRequestModeInternalEnumDTO("auto-on");

        public FrameRecordingSettingsRequestModeInternalEnumDTO(string value)
        {
            Value = value;
        }

        public FrameRecordingSettingsRequestModeInternalEnumDTO Parse(string value) => new FrameRecordingSettingsRequestModeInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(FrameRecordingSettingsRequestModeInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is FrameRecordingSettingsRequestModeInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(FrameRecordingSettingsRequestModeInternalEnumDTO left, FrameRecordingSettingsRequestModeInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(FrameRecordingSettingsRequestModeInternalEnumDTO left, FrameRecordingSettingsRequestModeInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator FrameRecordingSettingsRequestModeInternalEnumDTO(string value) => new FrameRecordingSettingsRequestModeInternalEnumDTO(value);

        public static implicit operator string(FrameRecordingSettingsRequestModeInternalEnumDTO type) => type.Value;
    }
}
