//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class GeolocationResultInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("accuracy_radius", Required = Newtonsoft.Json.Required.Default)]
        public int AccuracyRadius { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("city", Required = Newtonsoft.Json.Required.Default)]
        public string City { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("continent", Required = Newtonsoft.Json.Required.Default)]
        public string Continent { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("continent_code", Required = Newtonsoft.Json.Required.Default)]
        public string ContinentCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("country", Required = Newtonsoft.Json.Required.Default)]
        public string Country { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("country_iso_code", Required = Newtonsoft.Json.Required.Default)]
        public string CountryIsoCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("latitude", Required = Newtonsoft.Json.Required.Default)]
        public float Latitude { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("longitude", Required = Newtonsoft.Json.Required.Default)]
        public float Longitude { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("subdivision", Required = Newtonsoft.Json.Required.Default)]
        public string Subdivision { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("subdivision_iso_code", Required = Newtonsoft.Json.Required.Default)]
        public string SubdivisionIsoCode { get; set; } = default!;

    }

}

