//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class ImagesInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("fixed_height", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedHeight { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("fixed_height_downsampled", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedHeightDownsampled { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("fixed_height_still", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedHeightStill { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("fixed_width", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedWidth { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("fixed_width_downsampled", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedWidthDownsampled { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("fixed_width_still", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO FixedWidthStill { get; set; } = new ImageDataInternalDTO();

        [Newtonsoft.Json.JsonProperty("original", Required = Newtonsoft.Json.Required.Default)]
        public ImageDataInternalDTO Original { get; set; } = new ImageDataInternalDTO();

    }

}

