//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct NoiseCancellationSettingsModeInternalEnumDTO : System.IEquatable<NoiseCancellationSettingsModeInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<NoiseCancellationSettingsModeInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly NoiseCancellationSettingsModeInternalEnumDTO Available = new NoiseCancellationSettingsModeInternalEnumDTO("available");
        public static readonly NoiseCancellationSettingsModeInternalEnumDTO Disabled = new NoiseCancellationSettingsModeInternalEnumDTO("disabled");
        public static readonly NoiseCancellationSettingsModeInternalEnumDTO Auto_On = new NoiseCancellationSettingsModeInternalEnumDTO("auto-on");

        public NoiseCancellationSettingsModeInternalEnumDTO(string value)
        {
            Value = value;
        }

        public NoiseCancellationSettingsModeInternalEnumDTO Parse(string value) => new NoiseCancellationSettingsModeInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(NoiseCancellationSettingsModeInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is NoiseCancellationSettingsModeInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(NoiseCancellationSettingsModeInternalEnumDTO left, NoiseCancellationSettingsModeInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(NoiseCancellationSettingsModeInternalEnumDTO left, NoiseCancellationSettingsModeInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator NoiseCancellationSettingsModeInternalEnumDTO(string value) => new NoiseCancellationSettingsModeInternalEnumDTO(value);

        public static implicit operator string(NoiseCancellationSettingsModeInternalEnumDTO type) => type.Value;
    }
}
