//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// All possibility of string to use
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct OwnCapabilityInternalEnumDTO : System.IEquatable<OwnCapabilityInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<OwnCapabilityInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly OwnCapabilityInternalEnumDTO Block_Users = new OwnCapabilityInternalEnumDTO("block-users");
        public static readonly OwnCapabilityInternalEnumDTO Change_MaxDuration = new OwnCapabilityInternalEnumDTO("change-max-duration");
        public static readonly OwnCapabilityInternalEnumDTO Create_Call = new OwnCapabilityInternalEnumDTO("create-call");
        public static readonly OwnCapabilityInternalEnumDTO Create_Reaction = new OwnCapabilityInternalEnumDTO("create-reaction");
        public static readonly OwnCapabilityInternalEnumDTO Enable_NoiseCancellation = new OwnCapabilityInternalEnumDTO("enable-noise-cancellation");
        public static readonly OwnCapabilityInternalEnumDTO End_Call = new OwnCapabilityInternalEnumDTO("end-call");
        public static readonly OwnCapabilityInternalEnumDTO Join_Backstage = new OwnCapabilityInternalEnumDTO("join-backstage");
        public static readonly OwnCapabilityInternalEnumDTO Join_Call = new OwnCapabilityInternalEnumDTO("join-call");
        public static readonly OwnCapabilityInternalEnumDTO Join_EndedCall = new OwnCapabilityInternalEnumDTO("join-ended-call");
        public static readonly OwnCapabilityInternalEnumDTO Mute_Users = new OwnCapabilityInternalEnumDTO("mute-users");
        public static readonly OwnCapabilityInternalEnumDTO Pin_ForEveryone = new OwnCapabilityInternalEnumDTO("pin-for-everyone");
        public static readonly OwnCapabilityInternalEnumDTO Read_Call = new OwnCapabilityInternalEnumDTO("read-call");
        public static readonly OwnCapabilityInternalEnumDTO Remove_CallMember = new OwnCapabilityInternalEnumDTO("remove-call-member");
        public static readonly OwnCapabilityInternalEnumDTO Screenshare = new OwnCapabilityInternalEnumDTO("screenshare");
        public static readonly OwnCapabilityInternalEnumDTO Send_Audio = new OwnCapabilityInternalEnumDTO("send-audio");
        public static readonly OwnCapabilityInternalEnumDTO Send_Video = new OwnCapabilityInternalEnumDTO("send-video");
        public static readonly OwnCapabilityInternalEnumDTO Start_BroadcastCall = new OwnCapabilityInternalEnumDTO("start-broadcast-call");
        public static readonly OwnCapabilityInternalEnumDTO Start_ClosedCaptionsCall = new OwnCapabilityInternalEnumDTO("start-closed-captions-call");
        public static readonly OwnCapabilityInternalEnumDTO Start_FrameRecordCall = new OwnCapabilityInternalEnumDTO("start-frame-record-call");
        public static readonly OwnCapabilityInternalEnumDTO Start_RecordCall = new OwnCapabilityInternalEnumDTO("start-record-call");
        public static readonly OwnCapabilityInternalEnumDTO Start_TranscriptionCall = new OwnCapabilityInternalEnumDTO("start-transcription-call");
        public static readonly OwnCapabilityInternalEnumDTO Stop_BroadcastCall = new OwnCapabilityInternalEnumDTO("stop-broadcast-call");
        public static readonly OwnCapabilityInternalEnumDTO Stop_ClosedCaptionsCall = new OwnCapabilityInternalEnumDTO("stop-closed-captions-call");
        public static readonly OwnCapabilityInternalEnumDTO Stop_FrameRecordCall = new OwnCapabilityInternalEnumDTO("stop-frame-record-call");
        public static readonly OwnCapabilityInternalEnumDTO Stop_RecordCall = new OwnCapabilityInternalEnumDTO("stop-record-call");
        public static readonly OwnCapabilityInternalEnumDTO Stop_TranscriptionCall = new OwnCapabilityInternalEnumDTO("stop-transcription-call");
        public static readonly OwnCapabilityInternalEnumDTO Update_Call = new OwnCapabilityInternalEnumDTO("update-call");
        public static readonly OwnCapabilityInternalEnumDTO Update_CallMember = new OwnCapabilityInternalEnumDTO("update-call-member");
        public static readonly OwnCapabilityInternalEnumDTO Update_CallPermissions = new OwnCapabilityInternalEnumDTO("update-call-permissions");
        public static readonly OwnCapabilityInternalEnumDTO Update_CallSettings = new OwnCapabilityInternalEnumDTO("update-call-settings");

        public OwnCapabilityInternalEnumDTO(string value)
        {
            Value = value;
        }

        public OwnCapabilityInternalEnumDTO Parse(string value) => new OwnCapabilityInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(OwnCapabilityInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is OwnCapabilityInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(OwnCapabilityInternalEnumDTO left, OwnCapabilityInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(OwnCapabilityInternalEnumDTO left, OwnCapabilityInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator OwnCapabilityInternalEnumDTO(string value) => new OwnCapabilityInternalEnumDTO(value);

        public static implicit operator string(OwnCapabilityInternalEnumDTO type) => type.Value;
    }
}
