//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class PollInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("Custom", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.Dictionary<string, object> Custom { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("allow_answers", Required = Newtonsoft.Json.Required.Default)]
        public bool AllowAnswers { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("allow_user_suggested_options", Required = Newtonsoft.Json.Required.Default)]
        public bool AllowUserSuggestedOptions { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("answers_count", Required = Newtonsoft.Json.Required.Default)]
        public int AnswersCount { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("created_at", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset CreatedAt { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("created_by", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public UserObjectInternalDTO CreatedBy { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("created_by_id", Required = Newtonsoft.Json.Required.Default)]
        public string CreatedById { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.Default)]
        public string Description { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("enforce_unique_vote", Required = Newtonsoft.Json.Required.Default)]
        public bool EnforceUniqueVote { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default)]
        public string Id { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("is_closed", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public bool IsClosed { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("latest_answers", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.List<PollVoteInternalDTO?> LatestAnswers { get; set; } = new System.Collections.Generic.List<PollVoteInternalDTO?>();

        [Newtonsoft.Json.JsonProperty("latest_votes_by_option", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<PollVoteInternalDTO?>> LatestVotesByOption { get; set; } = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<PollVoteInternalDTO?>>();

        [Newtonsoft.Json.JsonProperty("max_votes_allowed", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int MaxVotesAllowed { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Default)]
        public string Name { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("options", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.List<PollOptionInternalDTO?> Options { get; set; } = new System.Collections.Generic.List<PollOptionInternalDTO?>();

        [Newtonsoft.Json.JsonProperty("own_votes", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.List<PollVoteInternalDTO?> OwnVotes { get; set; } = new System.Collections.Generic.List<PollVoteInternalDTO?>();

        [Newtonsoft.Json.JsonProperty("updated_at", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset UpdatedAt { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("vote_count", Required = Newtonsoft.Json.Required.Default)]
        public int VoteCount { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("vote_counts_by_option", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.Dictionary<string, int> VoteCountsByOption { get; set; } = new System.Collections.Generic.Dictionary<string, int>();

        [Newtonsoft.Json.JsonProperty("voting_visibility", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string VotingVisibility { get; set; } = default!;

    }

}

