//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct RecordSettingsModeInternalEnumDTO : System.IEquatable<RecordSettingsModeInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<RecordSettingsModeInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly RecordSettingsModeInternalEnumDTO Available = new RecordSettingsModeInternalEnumDTO("available");
        public static readonly RecordSettingsModeInternalEnumDTO Disabled = new RecordSettingsModeInternalEnumDTO("disabled");
        public static readonly RecordSettingsModeInternalEnumDTO Auto_On = new RecordSettingsModeInternalEnumDTO("auto-on");

        public RecordSettingsModeInternalEnumDTO(string value)
        {
            Value = value;
        }

        public RecordSettingsModeInternalEnumDTO Parse(string value) => new RecordSettingsModeInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(RecordSettingsModeInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is RecordSettingsModeInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RecordSettingsModeInternalEnumDTO left, RecordSettingsModeInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(RecordSettingsModeInternalEnumDTO left, RecordSettingsModeInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator RecordSettingsModeInternalEnumDTO(string value) => new RecordSettingsModeInternalEnumDTO(value);

        public static implicit operator string(RecordSettingsModeInternalEnumDTO type) => type.Value;
    }
}
