//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal enum RecordSettingsRequestQualityInternalEnum
    {

        [System.Runtime.Serialization.EnumMember(Value = @"360p")]
        _360p = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"480p")]
        _480p = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"720p")]
        _720p = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"1080p")]
        _1080p = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"1440p")]
        _1440p = 4,

    }

}

