//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct RecordSettingsQualityInternalEnumDTO : System.IEquatable<RecordSettingsQualityInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<RecordSettingsQualityInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly RecordSettingsQualityInternalEnumDTO _360p = new RecordSettingsQualityInternalEnumDTO("360p");
        public static readonly RecordSettingsQualityInternalEnumDTO _480p = new RecordSettingsQualityInternalEnumDTO("480p");
        public static readonly RecordSettingsQualityInternalEnumDTO _720p = new RecordSettingsQualityInternalEnumDTO("720p");
        public static readonly RecordSettingsQualityInternalEnumDTO _1080p = new RecordSettingsQualityInternalEnumDTO("1080p");
        public static readonly RecordSettingsQualityInternalEnumDTO _1440p = new RecordSettingsQualityInternalEnumDTO("1440p");
        public static readonly RecordSettingsQualityInternalEnumDTO Portrait_360x640 = new RecordSettingsQualityInternalEnumDTO("portrait-360x640");
        public static readonly RecordSettingsQualityInternalEnumDTO Portrait_480x854 = new RecordSettingsQualityInternalEnumDTO("portrait-480x854");
        public static readonly RecordSettingsQualityInternalEnumDTO Portrait_720x1280 = new RecordSettingsQualityInternalEnumDTO("portrait-720x1280");
        public static readonly RecordSettingsQualityInternalEnumDTO Portrait_1080x1920 = new RecordSettingsQualityInternalEnumDTO("portrait-1080x1920");
        public static readonly RecordSettingsQualityInternalEnumDTO Portrait_1440x2560 = new RecordSettingsQualityInternalEnumDTO("portrait-1440x2560");

        public RecordSettingsQualityInternalEnumDTO(string value)
        {
            Value = value;
        }

        public RecordSettingsQualityInternalEnumDTO Parse(string value) => new RecordSettingsQualityInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(RecordSettingsQualityInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is RecordSettingsQualityInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RecordSettingsQualityInternalEnumDTO left, RecordSettingsQualityInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(RecordSettingsQualityInternalEnumDTO left, RecordSettingsQualityInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator RecordSettingsQualityInternalEnumDTO(string value) => new RecordSettingsQualityInternalEnumDTO(value);

        public static implicit operator string(RecordSettingsQualityInternalEnumDTO type) => type.Value;
    }
}
