//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct RTMPBroadcastRequestQualityInternalEnumDTO : System.IEquatable<RTMPBroadcastRequestQualityInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<RTMPBroadcastRequestQualityInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO _360p = new RTMPBroadcastRequestQualityInternalEnumDTO("360p");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO _480p = new RTMPBroadcastRequestQualityInternalEnumDTO("480p");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO _720p = new RTMPBroadcastRequestQualityInternalEnumDTO("720p");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO _1080p = new RTMPBroadcastRequestQualityInternalEnumDTO("1080p");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO _1440p = new RTMPBroadcastRequestQualityInternalEnumDTO("1440p");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO Portrait_360x640 = new RTMPBroadcastRequestQualityInternalEnumDTO("portrait-360x640");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO Portrait_480x854 = new RTMPBroadcastRequestQualityInternalEnumDTO("portrait-480x854");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO Portrait_720x1280 = new RTMPBroadcastRequestQualityInternalEnumDTO("portrait-720x1280");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO Portrait_1080x1920 = new RTMPBroadcastRequestQualityInternalEnumDTO("portrait-1080x1920");
        public static readonly RTMPBroadcastRequestQualityInternalEnumDTO Portrait_1440x2560 = new RTMPBroadcastRequestQualityInternalEnumDTO("portrait-1440x2560");

        public RTMPBroadcastRequestQualityInternalEnumDTO(string value)
        {
            Value = value;
        }

        public RTMPBroadcastRequestQualityInternalEnumDTO Parse(string value) => new RTMPBroadcastRequestQualityInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(RTMPBroadcastRequestQualityInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is RTMPBroadcastRequestQualityInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RTMPBroadcastRequestQualityInternalEnumDTO left, RTMPBroadcastRequestQualityInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(RTMPBroadcastRequestQualityInternalEnumDTO left, RTMPBroadcastRequestQualityInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator RTMPBroadcastRequestQualityInternalEnumDTO(string value) => new RTMPBroadcastRequestQualityInternalEnumDTO(value);

        public static implicit operator string(RTMPBroadcastRequestQualityInternalEnumDTO type) => type.Value;
    }
}
