//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct RTMPSettingsRequestQualityInternalEnumDTO : System.IEquatable<RTMPSettingsRequestQualityInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<RTMPSettingsRequestQualityInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly RTMPSettingsRequestQualityInternalEnumDTO _360p = new RTMPSettingsRequestQualityInternalEnumDTO("360p");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO _480p = new RTMPSettingsRequestQualityInternalEnumDTO("480p");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO _720p = new RTMPSettingsRequestQualityInternalEnumDTO("720p");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO _1080p = new RTMPSettingsRequestQualityInternalEnumDTO("1080p");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO _1440p = new RTMPSettingsRequestQualityInternalEnumDTO("1440p");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO Portrait_360x640 = new RTMPSettingsRequestQualityInternalEnumDTO("portrait-360x640");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO Portrait_480x854 = new RTMPSettingsRequestQualityInternalEnumDTO("portrait-480x854");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO Portrait_720x1280 = new RTMPSettingsRequestQualityInternalEnumDTO("portrait-720x1280");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO Portrait_1080x1920 = new RTMPSettingsRequestQualityInternalEnumDTO("portrait-1080x1920");
        public static readonly RTMPSettingsRequestQualityInternalEnumDTO Portrait_1440x2560 = new RTMPSettingsRequestQualityInternalEnumDTO("portrait-1440x2560");

        public RTMPSettingsRequestQualityInternalEnumDTO(string value)
        {
            Value = value;
        }

        public RTMPSettingsRequestQualityInternalEnumDTO Parse(string value) => new RTMPSettingsRequestQualityInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(RTMPSettingsRequestQualityInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is RTMPSettingsRequestQualityInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(RTMPSettingsRequestQualityInternalEnumDTO left, RTMPSettingsRequestQualityInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(RTMPSettingsRequestQualityInternalEnumDTO left, RTMPSettingsRequestQualityInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator RTMPSettingsRequestQualityInternalEnumDTO(string value) => new RTMPSettingsRequestQualityInternalEnumDTO(value);

        public static implicit operator string(RTMPSettingsRequestQualityInternalEnumDTO type) => type.Value;
    }
}
