//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct TranscriptionSettingsResponseLanguageInternalEnumDTO : System.IEquatable<TranscriptionSettingsResponseLanguageInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<TranscriptionSettingsResponseLanguageInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Auto = new TranscriptionSettingsResponseLanguageInternalEnumDTO("auto");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO En = new TranscriptionSettingsResponseLanguageInternalEnumDTO("en");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Fr = new TranscriptionSettingsResponseLanguageInternalEnumDTO("fr");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Es = new TranscriptionSettingsResponseLanguageInternalEnumDTO("es");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO De = new TranscriptionSettingsResponseLanguageInternalEnumDTO("de");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO It = new TranscriptionSettingsResponseLanguageInternalEnumDTO("it");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Nl = new TranscriptionSettingsResponseLanguageInternalEnumDTO("nl");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Pt = new TranscriptionSettingsResponseLanguageInternalEnumDTO("pt");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Pl = new TranscriptionSettingsResponseLanguageInternalEnumDTO("pl");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ca = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ca");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Cs = new TranscriptionSettingsResponseLanguageInternalEnumDTO("cs");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Da = new TranscriptionSettingsResponseLanguageInternalEnumDTO("da");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO El = new TranscriptionSettingsResponseLanguageInternalEnumDTO("el");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Fi = new TranscriptionSettingsResponseLanguageInternalEnumDTO("fi");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Id = new TranscriptionSettingsResponseLanguageInternalEnumDTO("id");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ja = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ja");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ru = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ru");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Sv = new TranscriptionSettingsResponseLanguageInternalEnumDTO("sv");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ta = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ta");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Th = new TranscriptionSettingsResponseLanguageInternalEnumDTO("th");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Tr = new TranscriptionSettingsResponseLanguageInternalEnumDTO("tr");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Hu = new TranscriptionSettingsResponseLanguageInternalEnumDTO("hu");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ro = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ro");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Zh = new TranscriptionSettingsResponseLanguageInternalEnumDTO("zh");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ar = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ar");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Tl = new TranscriptionSettingsResponseLanguageInternalEnumDTO("tl");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO He = new TranscriptionSettingsResponseLanguageInternalEnumDTO("he");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Hi = new TranscriptionSettingsResponseLanguageInternalEnumDTO("hi");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Hr = new TranscriptionSettingsResponseLanguageInternalEnumDTO("hr");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ko = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ko");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Ms = new TranscriptionSettingsResponseLanguageInternalEnumDTO("ms");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO No = new TranscriptionSettingsResponseLanguageInternalEnumDTO("no");
        public static readonly TranscriptionSettingsResponseLanguageInternalEnumDTO Uk = new TranscriptionSettingsResponseLanguageInternalEnumDTO("uk");

        public TranscriptionSettingsResponseLanguageInternalEnumDTO(string value)
        {
            Value = value;
        }

        public TranscriptionSettingsResponseLanguageInternalEnumDTO Parse(string value) => new TranscriptionSettingsResponseLanguageInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(TranscriptionSettingsResponseLanguageInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is TranscriptionSettingsResponseLanguageInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(TranscriptionSettingsResponseLanguageInternalEnumDTO left, TranscriptionSettingsResponseLanguageInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(TranscriptionSettingsResponseLanguageInternalEnumDTO left, TranscriptionSettingsResponseLanguageInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator TranscriptionSettingsResponseLanguageInternalEnumDTO(string value) => new TranscriptionSettingsResponseLanguageInternalEnumDTO(value);

        public static implicit operator string(TranscriptionSettingsResponseLanguageInternalEnumDTO type) => type.Value;
    }
}
