//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal enum TranscriptionSettingsRequestLanguageInternalEnum
    {

        [System.Runtime.Serialization.EnumMember(Value = @"auto")]
        Auto = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"en")]
        En = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"fr")]
        Fr = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"es")]
        Es = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"de")]
        De = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"it")]
        It = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"nl")]
        Nl = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"pt")]
        Pt = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"pl")]
        Pl = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"ca")]
        Ca = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"cs")]
        Cs = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"da")]
        Da = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"el")]
        El = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"fi")]
        Fi = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"id")]
        Id = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"ja")]
        Ja = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"ru")]
        Ru = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"sv")]
        Sv = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"ta")]
        Ta = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"th")]
        Th = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"tr")]
        Tr = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"hu")]
        Hu = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"ro")]
        Ro = 22,

        [System.Runtime.Serialization.EnumMember(Value = @"zh")]
        Zh = 23,

        [System.Runtime.Serialization.EnumMember(Value = @"ar")]
        Ar = 24,

        [System.Runtime.Serialization.EnumMember(Value = @"tl")]
        Tl = 25,

        [System.Runtime.Serialization.EnumMember(Value = @"he")]
        He = 26,

        [System.Runtime.Serialization.EnumMember(Value = @"hi")]
        Hi = 27,

        [System.Runtime.Serialization.EnumMember(Value = @"hr")]
        Hr = 28,

        [System.Runtime.Serialization.EnumMember(Value = @"ko")]
        Ko = 29,

        [System.Runtime.Serialization.EnumMember(Value = @"ms")]
        Ms = 30,

        [System.Runtime.Serialization.EnumMember(Value = @"no")]
        No = 31,

        [System.Runtime.Serialization.EnumMember(Value = @"uk")]
        Uk = 32,

    }

}

