//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct TranscriptionSettingsRequestLanguageInternalEnumDTO : System.IEquatable<TranscriptionSettingsRequestLanguageInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<TranscriptionSettingsRequestLanguageInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Auto = new TranscriptionSettingsRequestLanguageInternalEnumDTO("auto");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO En = new TranscriptionSettingsRequestLanguageInternalEnumDTO("en");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Fr = new TranscriptionSettingsRequestLanguageInternalEnumDTO("fr");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Es = new TranscriptionSettingsRequestLanguageInternalEnumDTO("es");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO De = new TranscriptionSettingsRequestLanguageInternalEnumDTO("de");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO It = new TranscriptionSettingsRequestLanguageInternalEnumDTO("it");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Nl = new TranscriptionSettingsRequestLanguageInternalEnumDTO("nl");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Pt = new TranscriptionSettingsRequestLanguageInternalEnumDTO("pt");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Pl = new TranscriptionSettingsRequestLanguageInternalEnumDTO("pl");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ca = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ca");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Cs = new TranscriptionSettingsRequestLanguageInternalEnumDTO("cs");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Da = new TranscriptionSettingsRequestLanguageInternalEnumDTO("da");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO El = new TranscriptionSettingsRequestLanguageInternalEnumDTO("el");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Fi = new TranscriptionSettingsRequestLanguageInternalEnumDTO("fi");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Id = new TranscriptionSettingsRequestLanguageInternalEnumDTO("id");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ja = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ja");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ru = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ru");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Sv = new TranscriptionSettingsRequestLanguageInternalEnumDTO("sv");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ta = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ta");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Th = new TranscriptionSettingsRequestLanguageInternalEnumDTO("th");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Tr = new TranscriptionSettingsRequestLanguageInternalEnumDTO("tr");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Hu = new TranscriptionSettingsRequestLanguageInternalEnumDTO("hu");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ro = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ro");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Zh = new TranscriptionSettingsRequestLanguageInternalEnumDTO("zh");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ar = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ar");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Tl = new TranscriptionSettingsRequestLanguageInternalEnumDTO("tl");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO He = new TranscriptionSettingsRequestLanguageInternalEnumDTO("he");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Hi = new TranscriptionSettingsRequestLanguageInternalEnumDTO("hi");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Hr = new TranscriptionSettingsRequestLanguageInternalEnumDTO("hr");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ko = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ko");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Ms = new TranscriptionSettingsRequestLanguageInternalEnumDTO("ms");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO No = new TranscriptionSettingsRequestLanguageInternalEnumDTO("no");
        public static readonly TranscriptionSettingsRequestLanguageInternalEnumDTO Uk = new TranscriptionSettingsRequestLanguageInternalEnumDTO("uk");

        public TranscriptionSettingsRequestLanguageInternalEnumDTO(string value)
        {
            Value = value;
        }

        public TranscriptionSettingsRequestLanguageInternalEnumDTO Parse(string value) => new TranscriptionSettingsRequestLanguageInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(TranscriptionSettingsRequestLanguageInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is TranscriptionSettingsRequestLanguageInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(TranscriptionSettingsRequestLanguageInternalEnumDTO left, TranscriptionSettingsRequestLanguageInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(TranscriptionSettingsRequestLanguageInternalEnumDTO left, TranscriptionSettingsRequestLanguageInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator TranscriptionSettingsRequestLanguageInternalEnumDTO(string value) => new TranscriptionSettingsRequestLanguageInternalEnumDTO(value);

        public static implicit operator string(TranscriptionSettingsRequestLanguageInternalEnumDTO type) => type.Value;
    }
}
