//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct TranscriptionSettingsModeInternalEnumDTO : System.IEquatable<TranscriptionSettingsModeInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<TranscriptionSettingsModeInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly TranscriptionSettingsModeInternalEnumDTO Available = new TranscriptionSettingsModeInternalEnumDTO("available");
        public static readonly TranscriptionSettingsModeInternalEnumDTO Disabled = new TranscriptionSettingsModeInternalEnumDTO("disabled");
        public static readonly TranscriptionSettingsModeInternalEnumDTO Auto_On = new TranscriptionSettingsModeInternalEnumDTO("auto-on");

        public TranscriptionSettingsModeInternalEnumDTO(string value)
        {
            Value = value;
        }

        public TranscriptionSettingsModeInternalEnumDTO Parse(string value) => new TranscriptionSettingsModeInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(TranscriptionSettingsModeInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is TranscriptionSettingsModeInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(TranscriptionSettingsModeInternalEnumDTO left, TranscriptionSettingsModeInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(TranscriptionSettingsModeInternalEnumDTO left, TranscriptionSettingsModeInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator TranscriptionSettingsModeInternalEnumDTO(string value) => new TranscriptionSettingsModeInternalEnumDTO(value);

        public static implicit operator string(TranscriptionSettingsModeInternalEnumDTO type) => type.Value;
    }
}
