//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class UserStatsInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("info", Required = Newtonsoft.Json.Required.Default)]
        public UserInfoResponseInternalDTO Info { get; set; } = new UserInfoResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("min_event_ts", Required = Newtonsoft.Json.Required.Default)]
        public int MinEventTs { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("rating", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Rating { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("session_stats", Required = Newtonsoft.Json.Required.Default)]
        public System.Collections.Generic.List<UserSessionStatsInternalDTO> SessionStats { get; set; } = new System.Collections.Generic.List<UserSessionStatsInternalDTO>();

    }

}

