//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]

    internal readonly struct VideoSettingsCameraFacingInternalEnumDTO : System.IEquatable<VideoSettingsCameraFacingInternalEnumDTO>, StreamVideo.Core.LowLevelClient.IEnumeratedStruct<VideoSettingsCameraFacingInternalEnumDTO>
    {
        public string Value { get; }

        public static readonly VideoSettingsCameraFacingInternalEnumDTO Front = new VideoSettingsCameraFacingInternalEnumDTO("front");
        public static readonly VideoSettingsCameraFacingInternalEnumDTO Back = new VideoSettingsCameraFacingInternalEnumDTO("back");
        public static readonly VideoSettingsCameraFacingInternalEnumDTO External = new VideoSettingsCameraFacingInternalEnumDTO("external");

        public VideoSettingsCameraFacingInternalEnumDTO(string value)
        {
            Value = value;
        }

        public VideoSettingsCameraFacingInternalEnumDTO Parse(string value) => new VideoSettingsCameraFacingInternalEnumDTO(value);

        public override string ToString() => Value;

        public bool Equals(VideoSettingsCameraFacingInternalEnumDTO other) => Value == other.Value;

        public override bool Equals(object obj) => obj is VideoSettingsCameraFacingInternalEnumDTO other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public static bool operator ==(VideoSettingsCameraFacingInternalEnumDTO left, VideoSettingsCameraFacingInternalEnumDTO right) => left.Equals(right);

        public static bool operator !=(VideoSettingsCameraFacingInternalEnumDTO left, VideoSettingsCameraFacingInternalEnumDTO right) => !left.Equals(right);

        public static implicit operator VideoSettingsCameraFacingInternalEnumDTO(string value) => new VideoSettingsCameraFacingInternalEnumDTO(value);

        public static implicit operator string(VideoSettingsCameraFacingInternalEnumDTO type) => type.Value;
    }
}
