//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// Websocket auth message
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class WSAuthMessageInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("products", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.List<string> Products { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("token", Required = Newtonsoft.Json.Required.Default)]
        public string Token { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("user_details", Required = Newtonsoft.Json.Required.Default)]
        public ConnectUserDetailsRequestInternalDTO UserDetails { get; set; } = new ConnectUserDetailsRequestInternalDTO();

    }

}

