//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal enum CreateDeviceRequestPushProviderInternalEnum
    {

        [System.Runtime.Serialization.EnumMember(Value = @"firebase")]
        Firebase = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"apn")]
        Apn = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"huawei")]
        Huawei = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"xiaomi")]
        Xiaomi = 3,

    }

}

