//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class CredentialsInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("ice_servers", Required = Newtonsoft.Json.Required.Always)]
        public System.Collections.Generic.List<ICEServerInternalDTO> IceServers { get; set; } = new System.Collections.Generic.List<ICEServerInternalDTO>();

        [Newtonsoft.Json.JsonProperty("server", Required = Newtonsoft.Json.Required.Always)]
        public SFUResponseInternalDTO Server { get; set; } = new SFUResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("token", Required = Newtonsoft.Json.Required.Always)]
        public string Token { get; set; } = default!;

    }

}

