//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// All possibility of string to use
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal enum OwnCapability
    {

        [System.Runtime.Serialization.EnumMember(Value = @"block-users")]
        BlockUsers = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"create-call")]
        CreateCall = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"create-reaction")]
        CreateReaction = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"end-call")]
        EndCall = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"join-backstage")]
        JoinBackstage = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"join-call")]
        JoinCall = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"join-ended-call")]
        JoinEndedCall = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"mute-users")]
        MuteUsers = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"read-call")]
        ReadCall = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"remove-call-member")]
        RemoveCallMember = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"screenshare")]
        Screenshare = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"send-audio")]
        SendAudio = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"send-video")]
        SendVideo = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"start-broadcast-call")]
        StartBroadcastCall = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"start-record-call")]
        StartRecordCall = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"start-transcription-call")]
        StartTranscriptionCall = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"stop-broadcast-call")]
        StopBroadcastCall = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"stop-record-call")]
        StopRecordCall = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"stop-transcription-call")]
        StopTranscriptionCall = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"update-call")]
        UpdateCall = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"update-call-member")]
        UpdateCallMember = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"update-call-permissions")]
        UpdateCallPermissions = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"update-call-settings")]
        UpdateCallSettings = 22,

    }

}

