//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Responses;
using StreamVideo.Core.InternalDTO.Events;

namespace StreamVideo.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    public enum VideoSettingsCameraFacing
    {

        [System.Runtime.Serialization.EnumMember(Value = @"front")]
        Front = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"back")]
        Back = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"external")]
        External = 2,

    }

}

