//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Events;
using StreamVideo.Core.InternalDTO.Models;

namespace StreamVideo.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class CallStatsReportSummaryResponseInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("call_cid", Required = Newtonsoft.Json.Required.Always)]
        public string CallCid { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("call_session_id", Required = Newtonsoft.Json.Required.Always)]
        public string CallSessionId { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("call_status", Required = Newtonsoft.Json.Required.Always)]
        public string CallStatus { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("first_stats_time", Required = Newtonsoft.Json.Required.Always)]
        public System.DateTimeOffset FirstStatsTime { get; set; } = default!;

    }

}

