//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Events;
using StreamVideo.Core.InternalDTO.Models;

namespace StreamVideo.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class CallSettingsResponseInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("audio", Required = Newtonsoft.Json.Required.Default)]
        public AudioSettingsResponseInternalDTO Audio { get; set; } = new AudioSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("backstage", Required = Newtonsoft.Json.Required.Default)]
        public BackstageSettingsResponseInternalDTO Backstage { get; set; } = new BackstageSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("broadcasting", Required = Newtonsoft.Json.Required.Default)]
        public BroadcastSettingsResponseInternalDTO Broadcasting { get; set; } = new BroadcastSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("geofencing", Required = Newtonsoft.Json.Required.Default)]
        public GeofenceSettingsResponseInternalDTO Geofencing { get; set; } = new GeofenceSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("limits", Required = Newtonsoft.Json.Required.Default)]
        public LimitsSettingsResponseInternalDTO Limits { get; set; } = new LimitsSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("recording", Required = Newtonsoft.Json.Required.Default)]
        public RecordSettingsResponseInternalDTO Recording { get; set; } = new RecordSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("ring", Required = Newtonsoft.Json.Required.Default)]
        public RingSettingsResponseInternalDTO Ring { get; set; } = new RingSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("screensharing", Required = Newtonsoft.Json.Required.Default)]
        public ScreensharingSettingsResponseInternalDTO Screensharing { get; set; } = new ScreensharingSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("thumbnails", Required = Newtonsoft.Json.Required.Default)]
        public ThumbnailsSettingsResponseInternalDTO Thumbnails { get; set; } = new ThumbnailsSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("transcription", Required = Newtonsoft.Json.Required.Default)]
        public TranscriptionSettingsResponseInternalDTO Transcription { get; set; } = new TranscriptionSettingsResponseInternalDTO();

        [Newtonsoft.Json.JsonProperty("video", Required = Newtonsoft.Json.Required.Default)]
        public VideoSettingsResponseInternalDTO Video { get; set; } = new VideoSettingsResponseInternalDTO();

    }

}

