//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Events;
using StreamVideo.Core.InternalDTO.Models;

namespace StreamVideo.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class EdgeResponseInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("continent_code", Required = Newtonsoft.Json.Required.Default)]
        public string ContinentCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("country_iso_code", Required = Newtonsoft.Json.Required.Default)]
        public string CountryIsoCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("green", Required = Newtonsoft.Json.Required.Default)]
        public int Green { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Default)]
        public string Id { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("latency_test_url", Required = Newtonsoft.Json.Required.Default)]
        public string LatencyTestUrl { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("latitude", Required = Newtonsoft.Json.Required.Default)]
        public float Latitude { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("longitude", Required = Newtonsoft.Json.Required.Default)]
        public float Longitude { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("red", Required = Newtonsoft.Json.Required.Default)]
        public int Red { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("subdivision_iso_code", Required = Newtonsoft.Json.Required.Default)]
        public string SubdivisionIsoCode { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("yellow", Required = Newtonsoft.Json.Required.Default)]
        public int Yellow { get; set; } = default!;

    }

}

