//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Events;
using StreamVideo.Core.InternalDTO.Models;

namespace StreamVideo.Core.InternalDTO.Responses
{
    using System = global::System;

    /// <summary>
    /// Basic response information
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class QueryAggregateCallStatsResponseInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("call_duration_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CallDurationReportResponseInternalDTO CallDurationReport { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("call_participant_count_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CallParticipantCountReportResponseInternalDTO CallParticipantCountReport { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("calls_per_day_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CallsPerDayReportResponseInternalDTO CallsPerDayReport { get; set; } = default!;

        /// <summary>
        /// Duration of the request in milliseconds
        /// </summary>
        [Newtonsoft.Json.JsonProperty("duration", Required = Newtonsoft.Json.Required.Default)]
        public string Duration { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("network_metrics_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public NetworkMetricsReportResponseInternalDTO NetworkMetricsReport { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("quality_score_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public QualityScoreReportResponseInternalDTO QualityScoreReport { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sdk_usage_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public SDKUsageReportResponseInternalDTO SdkUsageReport { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("user_feedback_report", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public UserFeedbackReportResponseInternalDTO UserFeedbackReport { get; set; } = default!;

    }

}

