//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable


using StreamVideo.Core.InternalDTO.Requests;
using StreamVideo.Core.InternalDTO.Events;
using StreamVideo.Core.InternalDTO.Models;

namespace StreamVideo.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    internal partial class ReactionGroupResponseInternalDTO
    {
        [Newtonsoft.Json.JsonProperty("count", Required = Newtonsoft.Json.Required.Default)]
        public int Count { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("first_reaction_at", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset FirstReactionAt { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("last_reaction_at", Required = Newtonsoft.Json.Required.Default)]
        public System.DateTimeOffset LastReactionAt { get; set; } = default!;

        [Newtonsoft.Json.JsonProperty("sum_scores", Required = Newtonsoft.Json.Required.Default)]
        public int SumScores { get; set; } = default!;

    }

}

